export const SET_TITLE = '@feynamn/SET_TITLE'
export const TOGGLE_GRID = '@feynman/TOGGLE_GRID'
export const SET_GRID_SIZE = '@feynamn/SET_GRID_SIZE'
export const TOGGLE_HOTKEYS = '@feynman/TOGGLE_HOTKEYS'
export const TOGGLE_ANCHORS = '@feynman/TOGGLE_ACHORS'
export const TOGGLE_PATTERN_MODAL = '@feynman/TOGGLE_PATTERN_MODAL'
export const TOGGLE_PATTERN_INITIAL_VIS = '@feynman/TOGGLE_PATTERN_INITIAL_VIS'
export const TOGGLE_EXPORT_MODAL = '@feynman/TOGGLE_EXPORT_MODAL'
